// front-end-apps/react-test/src/routes/index.tsx
import {lazy} from 'react'
import {RouteObject} from 'react-router-dom'

const MainLayout = lazy(() => import('layouts/main-layout'))
const Main = lazy(() => import('pages/Main'))
const Sign = lazy(() => import('pages/Sign'))

export const routes: RouteObject[] = [
  {
    children: [
      {
        element: <Main />,
        index: true,
      },
      {
        element: <Sign />,
        path: 'sign',
      },
    ],
    element: <MainLayout />,
    path: '/',
  },
]

// front-end-apps/svelte-test/src/routes/Routes.svelte
<script>
  import {Route, Router} from 'svelte-routing'
  import MainLayout from 'layouts/main-layout/MainLayout.svelte'
  export let url = ''
</script>

<Router {url}>
  <Route path="/*">
    <MainLayout>
      <Route path="/" component="{() => import('pages/Main.svelte')}"></Route>
      <Route path="/sign" component="{() => import('pages/Sign.svelte')}"></Route>
    </MainLayout>
  </Route>
</Router>
